# © 2024 : github.com/NMoroney
# MIT License 
#

help :
	python3 simplex_to_png.py -h


noise :
	python3 simplex_to_png.py -o simplex_noise_2d.png -x 30 -y 20 -f 7.0 
	python3 simplex_to_png.py -o simplex_noise_2d.jpg -x 300 -y 200 -f 50.0 
#	python3 simplex_to_png.py -o simplex_noise_2d.png -x 300 -y 200 -f 50.0 
#	python3 simplex_to_png.py -o simplex_noise_2d.png -x 300 -y 200 -f 25.0 
#	python3 simplex_to_png.py -o simplex_noise_2d.png -x 600 -y 400 -f 75.0 


tsv :
	python3 simplex_to_tsv.py -o simplex_noise_2d.tsv -x 30 -y 20 -f 7.0 


