# [2401]
#

help :
	python3 tsv_to_contour.py -h


contour :
	python3 tsv_to_contour.py -i ../../data/simplex_noise_2d.tsv -o contour.jpg -t Simplex_noise 
#	python3 tsv_to_contour.py -i ../../data/simplex_noise_2d.tsv -o contour.png -t Simplex_noise 


